(() => {
  'use strict';
  const cfg=window.VALORAIA_CONFIG;if(!cfg||!window.supabase)return;
  const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lines=v=>Array.isArray(v)?v:typeof v==='string'?[v]:[];
  const categories='<option value="avaluos">Avalúos anteriores</option><option value="libro_verde">Libro Verde</option><option value="mercado">Mercado y costos</option><option value="normativa">Normativa</option><option value="general">General</option>';
  async function render(container,orgId,userId){
    let sources=[],timer;
    const active=()=>container.isConnected&&!!container.querySelector('#repository-list');
    const enabled=cfg.extendedAnalysisEnabled===true;
    const state=s=>{const e=s.analysis?.commercial_evidence;if(e?.complete)return `Analizado · ${e.completed_pages}/${e.page_count} páginas`;if(e)return `${s.status==='error'?'Error':'En proceso'} · ${e.completed_pages||0}/${e.page_count||'?'} páginas`;return s.status==='ready'?'Resumen anterior · requiere lectura con páginas':s.status==='processing'?'Proceso anterior sin avance registrado':s.status==='archived'?'Archivado':'Análisis pendiente';};
    const busy=s=>s.status==='processing'&&Date.now()-Date.parse(s.analysis?.commercial_evidence?.processed_at||s.analysis?.commercial_evidence?.started_at||'')<240000;
    const row=s=>`<article class="file-item" data-source-row="${s.id}"><div><strong>${esc(s.title)}</strong><br><span class="muted">${esc(s.file_name||s.source_url||'')} · ${esc(s.category)}</span><br><span class="repo-state">${esc(state(s))}</span>${s.error_message?'<p class="error-text">'+esc(s.error_message)+'</p>':''}</div><div class="actions"><button class="btn secondary" data-source-open="${s.id}">${s.source_type==='pdf'?'Abrir PDF':'Abrir enlace'}</button><button class="btn secondary" data-source-analysis="${s.id}">Ver análisis</button><button class="btn primary" data-source-analyze="${s.id}" ${busy(s)||!enabled?'disabled':''}>${busy(s)?'Analizando…':s.analysis?.commercial_evidence?.complete?'Verificar / actualizar':s.status==='error'||s.status==='processing'?'Reintentar':'Analizar todas las páginas'}</button><button class="btn secondary" data-source-archive="${s.id}">${s.status==='archived'?'Restaurar':'Archivar'}</button></div></article>`;
    container.innerHTML=`<section class="hero"><span class="badge">Repositorio privado de la organización</span><h1>Mis PDF y repositorio IA</h1><p>Los archivos originales y sus análisis se consultan aquí. La lectura completa registra las páginas de evidencia y distingue costos, valores de suelo, ofertas y avalúos anteriores.</p></section><div class="grid two"><section class="card"><h2>Cargar PDF</h2><form id="repo-pdf"><div class="field"><label>Título</label><input name="title" required></div><div class="field"><label>Categoría</label><select name="category">${categories}</select></div><div class="field"><label>PDF</label><input name="file" type="file" accept="application/pdf" required></div><button class="btn primary">${enabled?'Guardar y analizar':'Guardar fuente'}</button><div role="status" class="repo-save-message"></div></form><hr><h2>Agregar enlace</h2><form id="repo-url"><div class="field"><label>Título</label><input name="title" required></div><div class="field"><label>Categoría</label><select name="category">${categories}</select></div><div class="field"><label>Enlace público</label><input name="url" type="url" required></div><button class="btn secondary">${enabled?'Guardar y analizar':'Guardar fuente'}</button><div role="status" class="repo-save-message"></div></form></section><section class="card"><h2>Archivos y fuentes guardados</h2>${!enabled?'<p class="muted">La lectura verificable de todas las páginas está pendiente de activación. Puedes consultar los archivos y análisis ya guardados.</p>':''}<div id="repository-list">Consultando…</div></section></div><section id="repository-analysis"></section>`;
    async function analyze(id){const r=await db.functions.invoke('analyze-knowledge-source',{body:{source_id:id}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error.message);await refresh();}
    async function refresh(){
      if(!active()){clearTimeout(timer);return;}
      const r=await db.from('knowledge_sources').select('*').eq('organization_id',orgId).order('created_at',{ascending:false});
      if(!active())return;
      if(r.error){container.querySelector('#repository-list').innerHTML='<div class="status error">'+esc(r.error.message)+'</div>';return;}
      sources=r.data||[];container.querySelector('#repository-list').innerHTML=sources.map(row).join('')||'<p class="muted">Todavía no hay fuentes guardadas.</p>';
      container.querySelectorAll('[data-source-open]').forEach(b=>b.onclick=async()=>{const s=sources.find(x=>x.id===b.dataset.sourceOpen);try{if(s.source_type==='pdf'){if(!s.storage_path.startsWith(orgId+'/'))throw new Error('La ruta no corresponde a esta organización');const r=await db.storage.from('valuation-knowledge').createSignedUrl(s.storage_path,600);if(r.error)throw r.error;window.open(r.data.signedUrl,'_blank','noopener');}else{const u=new URL(s.source_url);if(!['http:','https:'].includes(u.protocol))throw new Error('Enlace no válido');window.open(u.toString(),'_blank','noopener');}}catch(e){alert(e.message);}});
      container.querySelectorAll('[data-source-analysis]').forEach(b=>b.onclick=()=>showAnalysis(sources.find(s=>s.id===b.dataset.sourceAnalysis)));
      container.querySelectorAll('[data-source-analyze]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Iniciando…';try{await analyze(b.dataset.sourceAnalyze);}catch(e){alert(e.message);b.disabled=false;b.textContent='Reintentar';}});
      container.querySelectorAll('[data-source-archive]').forEach(b=>b.onclick=async()=>{const s=sources.find(x=>x.id===b.dataset.sourceArchive),restore=s.status==='archived';if(!confirm(restore?'¿Restaurar esta fuente?':'¿Archivar esta fuente? El archivo se conserva y podrás restaurarlo.'))return;const r=await db.from('knowledge_sources').update({status:restore?'pending':'archived'}).eq('id',s.id);if(r.error)alert(r.error.message);else refresh();});
      clearTimeout(timer);if(sources.some(busy))timer=setTimeout(refresh,5000);
    }
    function showAnalysis(s){
      const a=s.analysis||{},e=a.commercial_evidence,pages=(e?.chunks||[]).flatMap(c=>c.analysis?.pages||[]),facts=lines(e?.facts||a.key_facts),prices=lines(e?.price_references);
      container.querySelector('#repository-analysis').innerHTML=`<section class="card"><h2>${esc(s.title)}</h2><div class="status">${esc(state(s))}</div>${!e?'<p>Este registro contiene un resumen anterior. Vuelve a analizarlo para verificar todas las páginas y utilizar sus cifras con trazabilidad en nuevos informes.</p>':''}<h3>Resumen</h3><p style="white-space:pre-wrap">${esc(e?.summary||a.summary||'No hay análisis guardado todavía.')}</p>${facts.length?'<h3>Datos extraídos</h3><div class="file-list">'+facts.map(f=>`<p>${esc(typeof f==='string'?f:(f.field_key||f.key||'Dato')+': '+JSON.stringify(f.value??f))}${f.page_number?' · página '+f.page_number:''}</p>`).join('')+'</div>':''}${prices.length?'<h3>Referencias de precios y antecedentes</h3>'+prices.map(p=>`<p><strong>${esc(p.title)}</strong><br>${esc(p.operation_type)} · ${esc(p.price_low!==null&&p.price_low!==undefined?`${p.price_low} a ${p.price_high}`:p.price)} ${esc(p.currency)} · ${esc(p.price_basis)} · ${esc(p.date||'Fecha no acreditada')} · página ${p.page_number}<br>${esc(p.evidence||'')}</p>`).join(''):''}<h3>Directrices y limitaciones</h3><p style="white-space:pre-wrap">${esc(lines(e?.valuation_guidance||a.valuation_guidance).join('\n'))}</p><p style="white-space:pre-wrap">${esc(lines(e?.warnings||a.limitations).join('\n'))}</p>${pages.length?'<details><summary>Páginas leídas y verificadas ('+pages.length+')</summary>'+pages.map(p=>'<p><strong>Página '+p.page_number+'</strong>: '+esc(p.summary)+'</p>').join('')+'</details>':''}</section>`;
      container.querySelector('#repository-analysis').scrollIntoView({behavior:'smooth'});
    }
    for(const id of ['repo-pdf','repo-url'])container.querySelector('#'+id).onsubmit=async event=>{
      event.preventDefault();const form=event.currentTarget,f=new FormData(form),button=form.querySelector('button'),msg=form.querySelector('.repo-save-message');button.disabled=true;msg.textContent='Guardando…';
      try{
        const source={organization_id:orgId,title:String(f.get('title')),category:String(f.get('category')),created_by:userId,status:'pending'};
        if(id==='repo-pdf'){const file=f.get('file'),path=orgId+'/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await db.storage.from('valuation-knowledge').upload(path,file,{contentType:'application/pdf'});if(u.error)throw u.error;Object.assign(source,{source_type:'pdf',storage_path:path,file_name:file.name,mime_type:'application/pdf'});}else{const url=new URL(String(f.get('url')));if(!['https:','http:'].includes(url.protocol))throw new Error('Introduce un enlace público http o https');Object.assign(source,{source_type:'url',source_url:url.toString()});}
        const r=await db.from('knowledge_sources').insert(source).select('id').single();if(r.error)throw r.error;if(enabled){msg.textContent='Fuente guardada. Iniciando lectura…';await analyze(r.data.id);}else await refresh();form.reset();msg.textContent=enabled?'Fuente guardada. Puedes ver el avance y el análisis en la lista.':'Fuente guardada. La lectura completa estará disponible al activar el análisis ampliado.';
      }catch(e){msg.textContent='No fue posible completar el proceso: '+e.message;}finally{button.disabled=false;}
    };
    await refresh();
  }
  window.ValoraIARepository={render};
})();
