(() => {
  'use strict';
  const root=document.getElementById('app'),cfg=window.VALORAIA_CONFIG;
  if(!cfg||!window.supabase){root.textContent='No se pudo cargar el expediente.';return;}
  const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey),id=new URLSearchParams(location.search).get('id');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={client_name:'Nombre del cliente',client_email:'Correo',client_phone:'Teléfono',property_type:'Tipo de inmueble',property_subtype:'Subtipo de inmueble',address_line:'Dirección',postal_code:'Código postal',locality:'Colonia o localidad',municipality:'Municipio',region:'Estado',land_area_m2:'Superficie de terreno (m²)',built_area_m2:'Superficie construida (m²)',bedrooms:'Recámaras',bathrooms:'Baños',parking_spaces:'Estacionamientos',floors:'Niveles',construction_year:'Año de construcción',conservation_state:'Estado de conservación',construction_quality:'Calidad constructiva',property_notes:'Descripción y observaciones',asking_price:'Precio solicitado',purpose:'Finalidad',invoice_requested:'Factura solicitada',invoice_name:'Razón social',invoice_rfc:'RFC',invoice_postal_code:'Código postal fiscal',invoice_regime:'Régimen fiscal',invoice_cfdi_use:'Uso de CFDI'};
  const statuses={draft:'En preparación',submitted:'Solicitud recibida',paid:'Pagado',in_review:'En revisión',completed:'Concluido',ready:'Disponible',pending:'Pendiente',needs_review:'Requiere revisión',processing:'En proceso',not_started:'Lectura pendiente',queued:'En espera'};
  let alive=true,timer;
  db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){alive=false;clearTimeout(timer);root.innerHTML='<section class="card"><h1>Acceso requerido</h1><a class="btn primary" href="cuenta.html">Ingresar a mi cuenta</a></section>';}});
  (async()=>{
    const user=await db.auth.getUser();if(!alive)return;
    if(user.error||!user.data.user){root.innerHTML='<section class="card"><h1>Acceso requerido</h1><a class="btn primary" href="cuenta.html">Ingresar a mi cuenta</a></section>';return;}
    const r=await db.from('service_requests').select('*,valuation_cases(*,properties(*))').eq('id',id).eq('created_by',user.data.user.id).single();if(!alive)return;
    if(r.error){root.innerHTML='<div class="status error">El expediente no está disponible para esta cuenta.</div>';return;}
    const request=r.data;
    root.innerHTML=`<section class="hero"><span class="badge">Expediente privado</span><h1>${esc(request.valuation_cases?.folio)}</h1><p>${request.service_type==='commercial'?'Opinión comercial':'Avalúo profesional con perito'} · ${esc(statuses[request.status]||request.status)}</p><a href="cuenta.html">Volver a mi cuenta</a></section><section class="card"><h2>Información proporcionada</h2><p>Estos son los datos guardados de tu solicitud.</p>${Object.entries(request.intake_data||{}).filter(([k])=>!/privacy|consent/.test(k)).map(([k,v])=>`<p><strong>${esc(labels[k]||k.replace(/_/g,' '))}</strong>: ${esc(v)}</p>`).join('')}</section><section class="card"><h2>Mis documentos</h2><div id="client-files"></div><form id="client-upload"><div class="field"><label>Tipo de documento</label><select name="category"><option value="escritura">Escritura</option><option value="plano">Plano</option><option value="predial">Predial</option><option value="fotografia">Fotografías</option><option value="otro">Otro</option></select></div><div class="field"><label>Agregar archivos</label><input name="files" type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" required></div><button class="btn secondary">Guardar documentos</button><div id="client-upload-state" role="status"></div></form></section><section class="card"><h2>Informe PDF</h2><div id="client-report-state"></div></section>`;
    async function files(){const r=await db.from('intake_documents').select('id,file_name,storage_path,status,analysis').eq('request_id',id);if(!alive||!document.getElementById('client-files'))return;if(r.error){document.getElementById('client-files').textContent='No fue posible consultar los documentos.';return;}document.getElementById('client-files').innerHTML=(r.data||[]).map((d,i)=>`<article class="file-item"><div><strong>${esc(d.file_name)}</strong><br>${d.analysis?.commercial_evidence?`${d.analysis.commercial_evidence.completed_pages||0}/${d.analysis.commercial_evidence.page_count||'?'} páginas leídas`:esc(d.status)}</div><button class="btn secondary" data-client-file="${i}">Abrir original</button></article>`).join('')||'<p class="muted">Aún no agregas documentos.</p>';document.querySelectorAll('[data-client-file]').forEach(b=>b.onclick=async()=>{const d=r.data[Number(b.dataset.clientFile)],signed=await db.storage.from('valuation-intake').createSignedUrl(d.storage_path,600);if(signed.error)alert(signed.error.message);else window.open(signed.data.signedUrl,'_blank','noopener');});}
    async function report(){if(!alive)return;const box=document.getElementById('client-report-state');if(request.service_type!=='commercial'){box.innerHTML='<p>El expediente profesional está en seguimiento por el perito. La entrega requiere su revisión y firma.</p>';return;}const result=await db.functions.invoke('commercial-request-status',{body:{request_id:id}});if(!alive||!box.isConnected)return;if(result.error||result.data?.error){box.textContent='No fue posible consultar el informe.';return;}const s=result.data;box.innerHTML=`<div class="status">${s.document_status==='ready'?'Informe disponible':s.document_status==='needs_review'?'Se requiere revisión antes de emitir una cifra':s.document_status==='generating'?'Analizando documentos y comparables':'Informe pendiente'}${s.outdated?'<br>Se agregaron o modificaron datos después de la emisión. Actualiza el informe para incorporarlos.':''}${s.source_title?'<br>'+esc(s.source_title)+' · '+(s.completed_pages||0)+'/'+(s.total_pages||'?')+' páginas':''}${s.review_reason?'<br>'+esc(s.review_reason):''}</div>${s.download_url?`<a class="btn primary" href="${esc(s.download_url)}" target="_blank" rel="noopener">Ver PDF completo${s.outdated?' anterior':''}</a>`:''}${cfg.extendedAnalysisEnabled===true&&s.payment_status==='paid'&&s.document_status!=='generating'?'<button class="btn secondary" id="update-client-report">Actualizar informe con mis datos</button>':''}`;
      const button=document.getElementById('update-client-report');if(button)button.onclick=async()=>{button.disabled=true;const result=await db.functions.invoke('generate-commercial-report',{body:{request_id:id,force:true}});if(result.error||result.data?.error){alert(result.data?.error||result.error.message);button.disabled=false;}else report();};
      clearTimeout(timer);if(s.document_status==='generating')timer=setTimeout(async()=>{await files();await report();},5000);
    }
    document.getElementById('client-upload').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,f=new FormData(form),button=form.querySelector('button'),message=document.getElementById('client-upload-state');button.disabled=true;message.textContent='Guardando…';try{for(const file of f.getAll('files').filter(f=>f.size)){const path=request.organization_id+'/'+id+'/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await db.storage.from('valuation-intake').upload(path,file,{contentType:file.type});if(u.error)throw u.error;const r=await db.from('intake_documents').insert({organization_id:request.organization_id,request_id:id,uploaded_by:user.data.user.id,category:String(f.get('category')),file_name:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size});if(r.error)throw r.error;}message.textContent='Documentos guardados. Actualiza el informe para incorporar la información nueva.';form.reset();await files();await report();}catch(e){message.textContent=e.message;}finally{button.disabled=false;}};
    await files();await report();
  })().catch(()=>{if(alive)root.innerHTML='<div class="status error">No fue posible abrir el expediente. Regresa a Mi cuenta y vuelve a intentarlo.</div>';});
})();
